; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
    default_envs = esp32debug

[env]
    platform = espressif32
    framework = arduino
    lib_deps = 
        https://github.com/tzapu/WiFiManager.git
        https://github.com/ESP32Async/ESPAsyncWebServer.git
        https://github.com/ESP32Async/AsyncTCP
        https://github.com/eModbus/eModbus.git
        SPI
    build_flags = -Wall -DLOG_LEVEL=LOG_LEVEL_DEBUG
    monitor_speed = 115200

[env:esp32debug]
    board = az-delivery-devkit-v4
    board_upload.flash_size = 4MB
    build_flags = ${env.build_flags} -Werror -DRX_PIN=18 -DTX_PIN=19

[env:esp32-s3-debug]
    board = esp32-s3-devkitc-1-n16r8v
    board_upload.flash_size = 16MB
    build_flags = ${env.build_flags} -Werror -DRX_PIN=11 -DTX_PIN=10
